version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - IV=${IV}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URI=${REDIS_URI}
